// SPDX-FileCopyrightText: Retroshare Team <contact@retroshare.cc>
// SPDX-License-Identifier: CC-BY-SA-4.0

= RetroShare

RetroShare is a decentralized, private, secure, cross-platform, communication
toolkit.
RetroShare provides filesharing, chat, messages, forums, channels and more.

.Build Status
|===============================================================================
|GNU/Linux, MacOS, (via travis-ci) | image:https://travis-ci.org/RetroShare/RetroShare.svg?branch=master[link="https://travis-ci.org/RetroShare/RetroShare"]
|Windows (via appveyor) | image:https://ci.appveyor.com/api/projects/status/github/RetroShare/RetroShare?svg=true[link="https://ci.appveyor.com/project/RetroShare58622/retroshare"]
|===============================================================================


== Compilation

It is very difficult to keep a comprehensive (we support many platforms) and
updated documentation on how to build RetroShare, instead we provide scripts and
recipes that are used to create the packages for the supported platforms and
more in the `build_scripts` directory of this repository.

Those packaging receipts together with the continuous integration files
`.travis.yml` and `appveyor.yml` are a good source of knowledge on how to
compile RetroShare on different platforms.


== Using RetroShare on a headless computer with WebUI

WARNING: This section is outdated need to be adapted to new WebUI

The webUI needs to be enabled as a parameter option in retroshare-service:

[source,bash]
--------
./retroshare-nogui --webinterface 9090 --docroot /usr/share/retroshare/webui/
--------

The webUI is only accessible on localhost:9090. It is advised to keep it that way so that your RS
cannot be controlled using an untrusted connection.

To access your web UI from a distance, just open a SSH tunnel on it:

[source,bash]
--------
distant_machine:~/ >  ssh rs_host -L 9090:localhost:9090 -N
--------

"rs_host" is the machine running retroshare-nogui. Then on the distant machine, access your webUI on 


      http://localhost:9090

That also works with a retroshare GUI of course.
