# FLTKGUI is not required for the Qt4,0 gui.
#

all:
	make -C	util
	make -C tcponudp
	make -C	serialiser
	make -C pqi
	make -C	dbase
	make -C	services
	make -C	dht
	make -C	upnp
	make -C	server
	make -C	rsserver
	make -C	rsiface

clean:
	make -C	util clean
	make -C tcponudp clean
	make -C	serialiser clean
	make -C pqi clean
	make -C	dbase clean
	make -C	services clean
	make -C	dht clean
	make -C	upnp clean
	make -C	server clean
	make -C	rsserver clean
	make -C	rsiface clean

clobber:
	make -C	util clobber
	make -C tcponudp clobber
	make -C	serialiser clobber
	make -C pqi clobber
	make -C	dbase clobber
	make -C	services clobber
	make -C	dht clobber
	make -C	upnp clobber
	make -C	server clobber
	make -C	rsserver clobber
	make -C	rsiface clobber

