#ifndef POSTEDUSERTYPES_H
#define POSTEDUSERTYPES_H

#define TOKEN_USER_TYPE_POST 4
#define TOKEN_USER_TYPE_VOTE 5
#define TOKEN_USER_TYPE_TOPIC 6
#define TOKEN_USER_TYPE_POST_MOD 7
#define TOKEN_USER_TYPE_POST_RANKINGS 8

#endif // POSTEDUSERTYPES_H
