
RS_TOP_DIR = ..
##### Define any flags that are needed for this section #######
###############################################################

###############################################################
include $(RS_TOP_DIR)/scripts/config.mk
###############################################################

RSOBJ  = p3service.o p3chatservice.o p3msgservice.o \
	p3gamelauncher.o p3ranking.o p3disc.o \
	p3photoservice.o \
	p3forums.o \
	p3status.o \
	p3Qblog.o

#	p3distrib.o

#TESTOBJ  = 

#TESTS  = 

all: librs tests

#tlvbase_test : tlvbase_test.o
#	$(CC) $(CFLAGS) -o tlvbase_test tlvbase_test.o $(OBJ) $(LIBS) 


###############################################################
include $(RS_TOP_DIR)/scripts/rules.mk
###############################################################

