/* generated by configure from include/openpgpsdk/configure.h.template. Don't edit. */

#define HAVE_ALLOCA_H 0
#define TIME_T_FMT	"%ld"

/* for silencing unused parameter warnings */
#define OPS_USED(x)	(x)=(x)
