#ifndef PROPORTIONEN_H
#define PROPORTIONEN_H

// fuer Basisstapel
#define BASISSTAPEL_AUSTEILSTAPEL "austeilstapel"
#define BASISSTAPEL_AUSTEILCOSTAPEL "austeilcostapel"
#define BASISSTAPEL_ZIELSTAPEL "zielstapel"
#define BASISSTAPEL_ABLAGESTAPEL "ablagestapel"
#define BASISSTAPEL_ABSTAND_HILFSZEIGER_VERHAELTNIS 28.0
#define BASISSTAPEL_ANZAHL_SPEICHERELEMENTE 2
#define BASISSTAPEL_SAVE_ID_IDX 0
#define BASISSTAPEL_KARTEN_IDX 1
#define BASISSTAPEL_KARTEN_SPLITTER ","

// fuer Ablagestapel
#define ABLAGESTAPEL_YDRIFT_VERHAELTNIS 9.333333333333333


// fuer Austeilcostapel
#define AUSTEILCOSTAPEL_XDRIFT_VERHAELTNIS 7.0

// muss um 1 groesser sein als BASISSTAPEL_KARTEN_IDX !!!
#define AUSTEILSTAPEL_ABLAGENUMMER_IDX 2

// muss um mindestens 1 groesser sein als BASISSTAPEL_ANZAHL_SPEICHERELEMENTE !!!
#define AUSTEILSTAPEL_ANZAHL_SPEICHERELEMENTE 3

// fuer Highscore
#define HIGHSCORE_NAME_POSITION 0
#define HIGHSCORE_PUNKTE_POSITION 1
#define HIGHSCORE_ZEIT_POSITION 2
#define HIGHSCORE_ZEILEN 15
#define HIGHSCORE_LEER "n / a"
#define HIGHSCORE_SPLITTER ":"
#define HIGHSCORE_NAME_SPALTE_STANDARTGROESSE 250


// fuer Hilfszeiger
#define HILFSZEIGER_BREITE_VERHAELTNIS 6.0
#define HILFSZEIGER_HOEHE_VERHAELTNIS 7.0
#define HILFSZEIGER_DICKE_VERHAELTNIS 70


// fuer Karten
#define KARTEN_KREUTZ "kreutz"
#define KARTEN_PIK "pik"
#define KARTEN_HERZ "herz"
#define KARTEN_KARO "karo"
#define KARTEN_ASS "ass"
#define KARTEN_BUBE "bube"
#define KARTEN_DAME "dame"
#define KARTEN_KOENIG "koenig"
#define KARTE_ANZAHL_SPEICHERELEMENTE 2
#define KARTE_SAVE_ID_IDX 0
#define KARTE_IST_VORNE_IDX 1
#define KARTE_VERHAELTNIS_BREITE_ZU_HOEHE 1.555555555555556


// fuer Punktezaehler
// punkte wenn nur eine karte gezogen wird
#define PUNKTEZAEHLER_EINE_ZIEHEN_AUSTEILSTAPEL_ZU_ABLAGESTAPEL 5
#define PUNKTEZAEHLER_EINE_ZIEHEN_AUSTEILSTAPEL_ZU_ZIELSTAPEL 15
#define PUNKTEZAEHLER_EINE_ZIEHEN_ABLAGESTAPEL_ZU_ZIELSTAPEL 10
#define PUNKTEZAEHLER_EINE_ZIEHEN_PUNKTEABZUG_ZEIT 2
#define PUNKTEZAEHLER_EINE_ZIEHEN_KARTE_AUF_ABLAGESTAPEL_AUFGEDECKT 5
#define PUNKTEZAEHLER_EINE_ZIEHEN_AUSTEILSTAPEL_DURCH 100

// punkte wenn drei karten gezogen werden
#define PUNKTEZAEHLER_DREI_ZIEHEN_AUSTEILSTAPEL_ZU_ABLAGESTAPEL 5
#define PUNKTEZAEHLER_DREI_ZIEHEN_AUSTEILSTAPEL_ZU_ZIELSTAPEL 15
#define PUNKTEZAEHLER_DREI_ZIEHEN_ABLAGESTAPEL_ZU_ZIELSTAPEL 10
#define PUNKTEZAEHLER_DREI_ZIEHEN_PUNKTEABZUG_ZEIT 1
#define PUNKTEZAEHLER_DREI_ZIEHEN_KARTE_AUF_ABLAGESTAPEL_AUFGEDECKT 5
#define PUNKTEZAEHLER_DREI_ZIEHEN_AUSTEILSTAPEL_DURCH 50

#define PUNKTEZAEHLER_SPLITTER "<<<"

#define PUNKTEZAEHLER_ANZAHL_SPEICHERELEMENTE 4
#define PUNKTEZAEHLER_STRING_SPLITTER ","
#define PUNKTEZAEHLER_SAVE_ID_IDX 0
#define PUNKTEZAEHLER_STRAFTIMER_ON_IDX 1
#define PUNKTEZAEHLER_NACH_OBEN_LISTE_IDX 2
#define PUNKTEZAEHLER_PUNKTE_IDX 3


// fuer Rahmen
#define RAHMEN_DICKE_VERHAELTNIS 23.333333333333333
#define RAHMEN_ECKRADIUS_VERHAELTNIS 9.333333333333333

// fuer Scene
#define SCENE_ABLAGE_STAPELZAHL 7
#define SCENE_ANZAHL_SPEICHERELEMENTE 3
#define SCENE_SAVE_ID_IDX 0
#define SCENE_EINE_ZIEHEN_IDX 1
#define SCENE_VERSTRICHENE_ZEIT_IDX 2
#define SCENE_AUSGANGSBREITE 795.0
#define SCENE_AUSGANGSHOEHE 595.0
#define SCENE_AUSTEILSTAPEL_X_VERHAELTNIS 34.565217391304348
#define SCENE_AUSTEILCOSTAPEL_X_VERHAELTNIS 5.977443609022556
#define SCENE_KREUTZZIELSTAPEL_X_VERHAELTNIS 2.252124645892351
#define SCENE_PIKZIELSTAPEL_X_VERHAELTNIS 1.717062634989201
#define SCENE_KAROZIELSTAPEL_X_VERHAELTNIS 1.387434554973822
#define SCENE_HERZZIELSTAPEL_X_VERHAELTNIS 1.16398243045388
#define SCENE_ABLAGESTAPEL_01_X_VERHAELTNIS 34.565217391304348
#define SCENE_ABLAGESTAPEL_02_X_VERHAELTNIS 5.977443609022556
#define SCENE_ABLAGESTAPEL_03_X_VERHAELTNIS 3.271604938271605
#define SCENE_ABLAGESTAPEL_04_X_VERHAELTNIS 2.252124645892351
#define SCENE_ABLAGESTAPEL_05_X_VERHAELTNIS 1.717062634989201
#define SCENE_ABLAGESTAPEL_06_X_VERHAELTNIS 1.387434554973822
#define SCENE_ABLAGESTAPEL_07_X_VERHAELTNIS 1.16398243045388
#define SCENE_ABLAGESTAPEL_Y_VERHAELTNIS 3.305555555555556
#define SCENE_VERHAELTNIS_BREITE_ZU_HOEHE 1.336134453781513
#define SCENE_VERHAELTNIS_HOEHE_ZU_BREITE 0.748427672955975
#define SCENE_HOEHE_ZU_KARTENHOEHE 4.25
#define SCENE_OBERE_STAPEL_Y_VERHAELTNIS 59.5


// fuer Undo
#define ZUEGE_PRO_BEWEGUNG 1.0
#define ZUEGE_PRO_AUFDECKUNG 0.5
#define UNDO_LIMIT 3.0
#define ZUEGE_SPLITTER ","
#define ZUEGE_NACH_SPLITTER "."
#define UNDO_ANZAHL_SPEICHERELEMENTE 2
#define UNDO_SAVE_ID_IDX 0
#define UNDO_VERLAUF_IDX 1

#endif
