
RS_TOP_DIR = ..
##### Define any flags that are needed for this section #######
###############################################################

###############################################################
include $(RS_TOP_DIR)/scripts/config.mk
###############################################################

RSOBJ =   

TESTOBJ  = #ftcachetest.o

TESTS  = #ftcachetest

all: librs tests

#ftcachetest : ftcachetest.o $(OBJ)
#	$(CC) $(CFLAGS) -o ftcachetest ftcachetest.o $(OBJ) $(LIBS)

###############################################################
include $(RS_TOP_DIR)/scripts/rules.mk
###############################################################

